pull_request_rules:
  - name: "Template Test"
    conditions:
      - base=main
    actions:
      comment:
        message: |
          Math Test: {{ 7 * 7 }}
          PR Number: {{ number }}
          Author: {{ author }}
