pull_request_rules:
  - name: "Info Disclosure Test"
    conditions:
      - base=main
    actions:
      comment:
        message: |
          Author: {{ author }}
          PR Number: {{ number }}
          Repository: {{ repository }}
          Base Branch: {{ base }}
          Head Branch: {{ head }}
          Files: {{ files }}
          Title: {{ title }}
          Body: {{ body }}
