pull_request_rules:
  - name: "Working Disclosure"
    conditions:
      - base=main
    actions:
      comment:
        message: |
          PR Author: @{{ author }}
          PR #{{ number }}
          Branch: {{ head }} → {{ base }}
          Changed Files: {{ files }}
