pull_request_rules:
  - name: "Template Exploit"
    conditions:
      - base=main
    actions:
      comment:
        message: |
          Test 1: {{ 7 * 7 }}
          Test 2: {{ pull_request.title }}
          Test 3: {{ pull_request.raw }}
